# Icinga Web 2 Docker image | (c) 2020 Icinga GmbH | GPLv2+

name: Icinga Web 2 Docker image
inputs:
  dockerhub-token:
    default: ''
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - shell: bash
      run: sudo apt-get update

    - shell: bash
      run: sudo apt-get install -y qemu-user-static binfmt-support

    - shell: bash
      run: docker buildx create --use

    - if: inputs.dockerhub-token != ''
      env:
        PW: ${{ inputs.dockerhub-token }}
      shell: bash
      run: |
        docker login -u icingaadmin --password-stdin <<<"$PW"

    - if: github.event_name == 'release'
      shell: bash
      run: |
        '${{ github.action_path }}/build.bash' . release push "$(tr -d v <<<'${{ github.ref_name }}')"
        '${{ github.action_path }}/mktags.bash' '${{ github.ref_name }}'

    - if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
      shell: bash
      run: |
        '${{ github.action_path }}/build.bash' . snapshot push "$(tr / - <<<'${{ github.ref_name }}')"

    - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch' && github.event_name != 'schedule'
      shell: bash
      run: |
        '${{ github.action_path }}/build.bash' . snapshot all
