name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v1

      - run: docker buildx create --use

      - name: Icinga Web 2
        run: git clone https://github.com/Icinga/icingaweb2.git

      - name: Build
        run: ./build.bash ./icingaweb2
